from pathlib import Path

p = Path('.github/workflows/update-relaunch.yml')
s = p.read_text(encoding='utf-8')
old = '''          $legacyInstaller = Join-Path $env:RUNNER_TEMP 'VideoShelf-Setup-v1.7.3.exe'\n          Invoke-WebRequest -UseBasicParsing -Uri 'https://github.com/x0XP/VideoShelf/releases/download/v1.7.3/VideoShelf-Setup-v1.7.3.exe' -OutFile $legacyInstaller\n          $legacyHash = (Get-FileHash -Path $legacyInstaller -Algorithm SHA256).Hash.ToLowerInvariant()\n          if ($legacyHash -ne '671711fa068c8aeb31221cf97eb608c90424a96bf010dec6c4035022a2085b02') {\n            throw \"Unexpected v1.7.3 installer hash: $legacyHash\"\n          }\n'''
new = '''          $headers = @{ 'User-Agent' = 'VideoShelf-CI' }\n          $previousRelease = Invoke-RestMethod -UseBasicParsing -Headers $headers -Uri 'https://api.github.com/repos/x0XP/VideoShelf/releases/latest'\n          if ($null -eq $previousRelease -or [string]::IsNullOrWhiteSpace($previousRelease.tag_name)) { throw 'Could not resolve the previous public VideoShelf release.' }\n          $asset = @($previousRelease.assets | Where-Object { $_.name -like 'VideoShelf-Setup-v*.exe' }) | Select-Object -First 1\n          if ($null -eq $asset) { throw \"No installer asset was found on previous release $($previousRelease.tag_name).\" }\n          $legacyInstaller = Join-Path $env:RUNNER_TEMP $asset.name\n          Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri $asset.browser_download_url -OutFile $legacyInstaller\n          if (!(Test-Path $legacyInstaller) -or (Get-Item $legacyInstaller).Length -lt 1000000) { throw 'Previous release installer download was invalid.' }\n          $legacyHash = (Get-FileHash -Path $legacyInstaller -Algorithm SHA256).Hash.ToLowerInvariant()\n          if (-not [string]::IsNullOrWhiteSpace($asset.digest) -and $asset.digest -like 'sha256:*') {\n            $expectedHash = $asset.digest.Substring(7).ToLowerInvariant()\n            if ($legacyHash -ne $expectedHash) { throw \"Previous release installer hash mismatch: expected $expectedHash got $legacyHash\" }\n          }\n          Write-Host \"Testing upgrade from $($previousRelease.tag_name) using $($asset.name).\"\n'''
if old not in s:
    raise SystemExit('Hard-coded legacy release block was not found exactly once.')
if s.count(old) != 1:
    raise SystemExit(f'Expected one legacy release block, found {s.count(old)}.')
s = s.replace(old, new, 1)
s = s.replace("TransferHost self-test failed after v1.7.3 -> current upgrade.", "TransferHost self-test failed after previous-release -> current upgrade.")
p.write_text(s, encoding='utf-8')
