<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>VideoShelf.TransferHost</AssemblyName>
    <RootNamespace>VideoShelf.TransferHost</RootNamespace>
    <StartupObject>VideoShelf.TransferHost.EntryPoint</StartupObject>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoTorrent" Version="3.0.2" />
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>
</Project>
